name: ci
on: push
jobs:
  release:
    runs-on: ubuntu-20.04
    # only try releasing from the main branch
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        # https://github.com/actions/checkout
        uses: actions/checkout@v3

      - name: Install 📦
        # https://github.com/bahmutov/npm-install
        uses: bahmutov/npm-install@v1

      - name: Semantic Release 🚀
        uses: cycjimmy/semantic-release-action@v3
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
